// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ42zY2BDGwnWEASIe-3PUP8Ksmyaq72c',
    appId: '1:877548370261:web:772d50db0cb6a5ebb997dc',
    messagingSenderId: '877548370261',
    projectId: 'ditonton-app-4ed0e',
    authDomain: 'ditonton-app-4ed0e.firebaseapp.com',
    storageBucket: 'ditonton-app-4ed0e.appspot.com',
    measurementId: 'G-2HG5XJTMQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRW7Tw8Ai8Obwr1rZQNGLOf6wggFoVPq4',
    appId: '1:877548370261:android:f78a3ed488dd6920b997dc',
    messagingSenderId: '877548370261',
    projectId: 'ditonton-app-4ed0e',
    storageBucket: 'ditonton-app-4ed0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTNeDc1Xu28UUDbmtmohx909LHy8d1UY',
    appId: '1:877548370261:ios:f8258f7b115bfcccb997dc',
    messagingSenderId: '877548370261',
    projectId: 'ditonton-app-4ed0e',
    storageBucket: 'ditonton-app-4ed0e.appspot.com',
    iosClientId: '877548370261-b9h34ompvgcr74ul7vftmi5slhi7j09o.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
