// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEchB2_WKds3hlT4Sf42dK5BmHMJgHu_A',
    appId: '1:803097104855:web:b132825c5b43827bde3b92',
    messagingSenderId: '803097104855',
    projectId: 'ditonton-89d8c',
    authDomain: 'ditonton-89d8c.firebaseapp.com',
    storageBucket: 'ditonton-89d8c.appspot.com',
    measurementId: 'G-18PHM98TPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnoewxJyn6vhLY7gyd5d3c6XRnMJiF8M',
    appId: '1:803097104855:android:0268ebf1c94ea432de3b92',
    messagingSenderId: '803097104855',
    projectId: 'ditonton-89d8c',
    storageBucket: 'ditonton-89d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hvM5Y6HBQAGM4d2xbFGAY9nNDjNiRwo',
    appId: '1:803097104855:ios:b7be3c5ba0da3f7cde3b92',
    messagingSenderId: '803097104855',
    projectId: 'ditonton-89d8c',
    storageBucket: 'ditonton-89d8c.appspot.com',
    iosClientId: '803097104855-btvfl52mijshfn9i0aafdpavjqap0c8j.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
