// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i26;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i9;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i16;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i14;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i12;
import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i24;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i22;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i13;
import 'package:ditonton/data/models/movie_table.dart' as _i15;
import 'package:ditonton/data/models/tvseries/tv_series_details.dart' as _i4;
import 'package:ditonton/data/models/tvseries/tv_series_results.dart' as _i23;
import 'package:ditonton/data/models/tvseries/tv_series_table.dart' as _i18;
import 'package:ditonton/domain/entities/movie.dart' as _i10;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i11;
import 'package:ditonton/domain/entities/tv_details.dart' as _i21;
import 'package:ditonton/domain/entities/tv_series.dart' as _i20;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i7;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i19;
import 'package:http/http.dart' as _i6;
import 'package:http/io_client.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailResponse_1 extends _i1.Fake
    implements _i3.MovieDetailResponse {}

class _FakeTvSeriesDetails_2 extends _i1.Fake implements _i4.TvSeriesDetails {}

class _FakeIOStreamedResponse_3 extends _i1.Fake
    implements _i5.IOStreamedResponse {}

class _FakeResponse_4 extends _i1.Fake implements _i6.Response {}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i7.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>
      fetchNowPlayingAllMovie() =>
          (super.noSuchMethod(Invocation.method(#fetchNowPlayingAllMovie, []),
                  returnValue:
                      Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                          _FakeEither_0<_i9.Failure, List<_i10.Movie>>()))
              as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>
      fetchPopularAllMovie() =>
          (super.noSuchMethod(Invocation.method(#fetchPopularAllMovie, []),
                  returnValue:
                      Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                          _FakeEither_0<_i9.Failure, List<_i10.Movie>>()))
              as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>
      fetchTopRatedAllMovie() =>
          (super.noSuchMethod(Invocation.method(#fetchTopRatedAllMovie, []),
                  returnValue:
                      Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                          _FakeEither_0<_i9.Failure, List<_i10.Movie>>()))
              as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>> fetchMovieDataDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchMovieDataDetail, [id]),
          returnValue: Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>.value(
              _FakeEither_0<_i9.Failure, _i11.MovieDetail>())) as _i8
          .Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>
      fetchMovieDataRecommendations(int? id) => (super.noSuchMethod(
          Invocation.method(#fetchMovieDataRecommendations, [id]),
          returnValue: Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
              _FakeEither_0<_i9.Failure, List<_i10.Movie>>())) as _i8
          .Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> findAllMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#findAllMovies, [query]),
          returnValue: Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
              _FakeEither_0<_i9.Failure, List<_i10.Movie>>())) as _i8
          .Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i9.Failure, String>>.value(
                  _FakeEither_0<_i9.Failure, String>()))
          as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> deleteFromWatchList(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#deleteFromWatchList, [movie]),
              returnValue: Future<_i2.Either<_i9.Failure, String>>.value(
                  _FakeEither_0<_i9.Failure, String>()))
          as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>
      fetchWatchListAllMovie() =>
          (super.noSuchMethod(Invocation.method(#fetchWatchListAllMovie, []),
                  returnValue:
                      Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
                          _FakeEither_0<_i9.Failure, List<_i10.Movie>>()))
              as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i12.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.MovieModel>> fetchNowPlayingAllMovie() =>
      (super.noSuchMethod(Invocation.method(#fetchNowPlayingAllMovie, []),
              returnValue:
                  Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<List<_i13.MovieModel>> fetchPopularAllMovie() =>
      (super.noSuchMethod(Invocation.method(#fetchPopularAllMovie, []),
              returnValue:
                  Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<List<_i13.MovieModel>> fetchTopRatedAllMovie() =>
      (super.noSuchMethod(Invocation.method(#fetchTopRatedAllMovie, []),
              returnValue:
                  Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<_i3.MovieDetailResponse> fetchMovieDataDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchMovieDataDetail, [id]),
              returnValue: Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1()))
          as _i8.Future<_i3.MovieDetailResponse>);
  @override
  _i8.Future<List<_i13.MovieModel>> fetchMovieDataRecommendations(int? id) =>
      (super.noSuchMethod(
              Invocation.method(#fetchMovieDataRecommendations, [id]),
              returnValue:
                  Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
  @override
  _i8.Future<List<_i13.MovieModel>> findAllMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#findAllMovies, [query]),
              returnValue:
                  Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]))
          as _i8.Future<List<_i13.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i14.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> addToWatchList(_i15.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#addToWatchList, [movie]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<String> deleteFromWatchList(_i15.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#deleteFromWatchList, [movie]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i15.MovieTable?> fetchMovieDataById(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchMovieDataById, [id]),
              returnValue: Future<_i15.MovieTable?>.value())
          as _i8.Future<_i15.MovieTable?>);
  @override
  _i8.Future<List<_i15.MovieTable>> fetchWatchListAllMovie() =>
      (super.noSuchMethod(Invocation.method(#fetchWatchListAllMovie, []),
              returnValue:
                  Future<List<_i15.MovieTable>>.value(<_i15.MovieTable>[]))
          as _i8.Future<List<_i15.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i16.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i17.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i17.Database?>.value())
          as _i8.Future<_i17.Database?>);
  @override
  _i8.Future<int> addToWatchList(_i15.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#addToWatchList, [movie]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<int> insertTvWatchlist(_i18.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchlist, [tvSeries]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<int> deleteFromWatchList(_i15.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#deleteFromWatchList, [movie]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<int> removeTvWatchlist(_i18.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [tvSeries]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<Map<String, dynamic>?> fetchMovieDataById(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchMovieDataById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<Map<String, dynamic>?> fetchTvSeriesDataById(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchTvSeriesDataById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<List<Map<String, dynamic>>> fetchWatchListAllMovie() =>
      (super.noSuchMethod(Invocation.method(#fetchWatchListAllMovie, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i8.Future<List<Map<String, dynamic>>>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getTvWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getTvWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i19.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>
      fetchNowPlayingTvSeriesData() => (super.noSuchMethod(
              Invocation.method(#fetchNowPlayingTvSeriesData, []),
              returnValue:
                  Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i20.TvSeries>>()))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>
      fetchPopularTvSeriesData() => (super.noSuchMethod(
              Invocation.method(#fetchPopularTvSeriesData, []),
              returnValue:
                  Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i20.TvSeries>>()))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>
      fetchTopRatedTvSeriesData() => (super.noSuchMethod(
              Invocation.method(#fetchTopRatedTvSeriesData, []),
              returnValue:
                  Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i20.TvSeries>>()))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i21.TvDetails>> fetchTvSeriesDataDetails(
          int? seriesId) =>
      (super.noSuchMethod(
          Invocation.method(#fetchTvSeriesDataDetails, [seriesId]),
          returnValue: Future<_i2.Either<_i9.Failure, _i21.TvDetails>>.value(
              _FakeEither_0<_i9.Failure, _i21.TvDetails>())) as _i8
          .Future<_i2.Either<_i9.Failure, _i21.TvDetails>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>
      fetchSearchTvSeriesData(String? query) => (super.noSuchMethod(
              Invocation.method(#fetchSearchTvSeriesData, [query]),
              returnValue:
                  Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i20.TvSeries>>()))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>
      fetchTvSeriesRecommendationsData(int? seriesId) => (super.noSuchMethod(
              Invocation.method(#fetchTvSeriesRecommendationsData, [seriesId]),
              returnValue:
                  Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i20.TvSeries>>()))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> addToWatchList(
          _i21.TvDetails? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#addToWatchList, [tvSeries]),
              returnValue: Future<_i2.Either<_i9.Failure, String>>.value(
                  _FakeEither_0<_i9.Failure, String>()))
          as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> deleteFromWatchList(
          _i21.TvDetails? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#deleteFromWatchList, [tvSeries]),
              returnValue: Future<_i2.Either<_i9.Failure, String>>.value(
                  _FakeEither_0<_i9.Failure, String>()))
          as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>
      fetchWatchListTvDataSeries() => (super.noSuchMethod(
              Invocation.method(#fetchWatchListTvDataSeries, []),
              returnValue:
                  Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>.value(
                      _FakeEither_0<_i9.Failure, List<_i20.TvSeries>>()))
          as _i8.Future<_i2.Either<_i9.Failure, List<_i20.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i22.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i23.TvSeriesResults>> fetchNowPlayingTvSeriesData() =>
      (super.noSuchMethod(Invocation.method(#fetchNowPlayingTvSeriesData, []),
              returnValue: Future<List<_i23.TvSeriesResults>>.value(
                  <_i23.TvSeriesResults>[]))
          as _i8.Future<List<_i23.TvSeriesResults>>);
  @override
  _i8.Future<List<_i23.TvSeriesResults>> fetchPopularTvSeriesData() =>
      (super.noSuchMethod(Invocation.method(#fetchPopularTvSeriesData, []),
              returnValue: Future<List<_i23.TvSeriesResults>>.value(
                  <_i23.TvSeriesResults>[]))
          as _i8.Future<List<_i23.TvSeriesResults>>);
  @override
  _i8.Future<List<_i23.TvSeriesResults>> fetchTopRatedTvSeriesData() =>
      (super.noSuchMethod(Invocation.method(#fetchTopRatedTvSeriesData, []),
              returnValue: Future<List<_i23.TvSeriesResults>>.value(
                  <_i23.TvSeriesResults>[]))
          as _i8.Future<List<_i23.TvSeriesResults>>);
  @override
  _i8.Future<_i4.TvSeriesDetails> fetchTvSeriesDataDetails(int? seriesId) =>
      (super.noSuchMethod(
              Invocation.method(#fetchTvSeriesDataDetails, [seriesId]),
              returnValue:
                  Future<_i4.TvSeriesDetails>.value(_FakeTvSeriesDetails_2()))
          as _i8.Future<_i4.TvSeriesDetails>);
  @override
  _i8.Future<List<_i23.TvSeriesResults>> fetchSearchTvSeriesData(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#fetchSearchTvSeriesData, [query]),
              returnValue: Future<List<_i23.TvSeriesResults>>.value(
                  <_i23.TvSeriesResults>[]))
          as _i8.Future<List<_i23.TvSeriesResults>>);
  @override
  _i8.Future<List<_i23.TvSeriesResults>> fetchTvSeriesRecommendationsData(
          int? seriesId) =>
      (super.noSuchMethod(
              Invocation.method(#fetchTvSeriesRecommendationsData, [seriesId]),
              returnValue: Future<List<_i23.TvSeriesResults>>.value(
                  <_i23.TvSeriesResults>[]))
          as _i8.Future<List<_i23.TvSeriesResults>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i24.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> addToWatchList(_i18.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#addToWatchList, [tvSeries]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<String> deleteFromWatchList(_i18.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#deleteFromWatchList, [tvSeries]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i18.TvSeriesTable?> fetchTvSeriesDataById(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchTvSeriesDataById, [id]),
              returnValue: Future<_i18.TvSeriesTable?>.value())
          as _i8.Future<_i18.TvSeriesTable?>);
  @override
  _i8.Future<List<_i18.TvSeriesTable>> fetchWatchListTvDataSeries() =>
      (super.noSuchMethod(Invocation.method(#fetchWatchListTvDataSeries, []),
          returnValue: Future<List<_i18.TvSeriesTable>>.value(
              <_i18.TvSeriesTable>[])) as _i8.Future<List<_i18.TvSeriesTable>>);
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.IOClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.IOStreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: Future<_i5.IOStreamedResponse>.value(
                  _FakeIOStreamedResponse_3()))
          as _i8.Future<_i5.IOStreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  _i8.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i25.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i26.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i26.Uint8List>.value(_i26.Uint8List(0)))
          as _i8.Future<_i26.Uint8List>);
}
